#!/bin/bash

echo "Setting up environment on a new host"
echo "Let's get vim/gvim working with Janus"
curl -Lo- http://bit.ly/janus-bootstrap | bash
echo "installing dot files"
rake install
echo "to repeat install later (e.g. after update). run rake install again"


